#!/usr/bin/sh
## declare an array variable
#test

declare -a arr=("xAttr" "xIntent" "xNeed" "xEffect" "xReact" "xWant" "oReact" "oEffect" "oWant")

while [ $# -gt 0 ]; do

	if [[ $1 == *"--"* ]]; then
		param="${1/--/}"
		declare $param="$2"
		# echo $1 $2 // Optional to see the parameter:value result
	fi

	shift
done

## now loop through the above array
if [ $1 = "-h" ]; then
    echo  "run --tag --lang --size --name"
   exit 1 
fi
for i in "${arr[@]}"
do
   echo "$i"
   if [ -z "$tag" ] || [ $tag = $i ] || [ $tag = "all" ]; then
	   sh run_fine_tune.sh ${lang}_train_${i}_other_${size}_per_prefix \
			    ${lang}_${i}_1k_validation_${name} \
			    labels.txt
   fi
done

# You can access them using echo "${arr[0]}", "${arr[1]}" also




