#!/usr/bin/sh
## declare an array variable
#test

declare -a arr=("xAttr" "xIntent" "xNeed" "xEffect" "xReact" "xWant" "oReact" "oEffect" "oWant")
while [ $# -gt 0 ]; do

        if [[ $1 == *"--"* ]]; then
                param="${1/--/}"
                value="${param##*=}"
                param="${param%%=*}"
                declare $param="$value"
                echo variable name: $param 
                eval echo variable content: '$'"$param"
        fi

        shift
done
valid=${valid:-validation}
lang=${lang:-en}
size=${size:-5k}
tag=${tag:-all}

## now loop through the above array
if [ $1 = "-h" ]; then
    echo  "run --tag --lang --size --valid"
   exit 1 
fi
echo  "run --tag=${tag} --lang=${lang} --size=${size} --valid=${valid}"
for i in "${arr[@]}"
do
   echo "$i"
   if [ -z "$tag" ] || [ $tag = $i ] || [ $tag = "all" ]; then
	   sh run_fine_tune.sh ${lang}_train_${i}_${size} \
			    ${lang}_${valid}_${i}_1k \
			    labels.txt
   fi
done

# You can access them using echo "${arr[0]}", "${arr[1]}" also




